### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by coreybruce** [zeldaret/tmc#608]
Hey just wanted to report a building issue

```
 make -j4
mkdir -p tools/cmake-build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=tools -S tools -B tools/cmake-build
CMake Warning (dev) at /usr/share/cmake/Modules/FetchContent.cmake:1282 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  CMakeLists.txt:9 (FetchContent_Declare)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The CXX compiler identification is GNU 12.1.0
-- The C compiler identification is GNU 12.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Module support is disabled.
-- Version: 8.0.1
-- Build type: Release
-- CXX_STANDARD: 17
-- Performing Test has_std_17_flag
-- Performing Test has_std_17_flag - Success
-- Performing Test has_std_1z_flag
-- Performing Test has_std_1z_flag - Success
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS
-- Performing Test SUPPORTS_USER_DEFINED_LITERALS - Success
-- Performing Test FMT_HAS_VARIANT
-- Performing Test FMT_HAS_VARIANT - Success
-- Required features: cxx_variadic_templates
-- Looking for strtod_l
-- Looking for strtod_l - not found
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.13")  
-- Found PNG: /usr/lib/libpng.so (found version "1.6.39") 
-- Configuring done (27.0s)
-- Generating done (0.1s)
-- Build files have been written to: /home/corey/stuff/projects/tmc/tools/cmake-build
cmake --build tools/cmake-build -j --target install
make[1]: warning: -j0 forced in submake: resetting jobserver mode.
[  1%] Building C object src/aif2pcm/CMakeFiles/aif2pcm.dir/extended.c.o
[  3%] Building C object src/aif2pcm/CMakeFiles/aif2pcm.dir/main.c.o
[  4%] Building CXX object src/util/CMakeFiles/util_dummy.dir/dummy.cpp.o
[  6%] Building CXX object src/agb2mid/CMakeFiles/agb2mid.dir/agb.cpp.o
[  8%] Building CXX object src/agb2mid/CMakeFiles/agb2mid.dir/error.cpp.o
[  9%] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/format.cc.o
[ 11%] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/os.cc.o
[ 12%] Building CXX object src/agb2mid/CMakeFiles/agb2mid.dir/midi.cpp.o
[ 14%] Building CXX object src/agb2mid/CMakeFiles/agb2mid.dir/main.cpp.o
[ 16%] Building C object src/gbafix/CMakeFiles/gbafix.dir/gbafix.c.o
[ 17%] Building CXX object src/agb2mid/CMakeFiles/agb2mid.dir/tables.cpp.o
[ 19%] Building C object src/bin2c/CMakeFiles/bin2c.dir/bin2c.c.o
[ 20%] Building C object src/gbagfx/CMakeFiles/gbagfx.dir/convert_png.c.o
[ 22%] Building C object src/gbagfx/CMakeFiles/gbagfx.dir/huff.c.o
[ 24%] Building C object src/gbagfx/CMakeFiles/gbagfx.dir/gfx.c.o
[ 30%] Building CXX object src/preproc/CMakeFiles/preproc.dir/asm_file.cpp.o
[ 25%] Building C object src/gbagfx/CMakeFiles/gbagfx.dir/font.c.o
[ 27%] Building C object src/gbagfx/CMakeFiles/gbagfx.dir/lz.c.o
[ 29%] Building C object src/gbagfx/CMakeFiles/gbagfx.dir/jasc_pal.c.o
[ 32%] Building CXX object src/mid2agb/CMakeFiles/mid2agb.dir/main.cpp.o
[ 33%] Building CXX object src/mid2agb/CMakeFiles/mid2agb.dir/tables.cpp.o
[ 35%] Building CXX object src/preproc/CMakeFiles/preproc.dir/charmap.cpp.o
[ 37%] Building CXX object src/mid2agb/CMakeFiles/mid2agb.dir/agb.cpp.o
[ 40%] Building C object src/gbagfx/CMakeFiles/gbagfx.dir/util.c.o
[ 40%] Building C object src/gbagfx/CMakeFiles/gbagfx.dir/rl.c.o
[ 41%] Building CXX object src/mid2agb/CMakeFiles/mid2agb.dir/error.cpp.o
[ 43%] Building CXX object src/preproc/CMakeFiles/preproc.dir/c_file.cpp.o
[ 45%] Building C object src/gbagfx/CMakeFiles/gbagfx.dir/main.c.o
[ 46%] Building CXX object src/mid2agb/CMakeFiles/mid2agb.dir/midi.cpp.o
[ 48%] Building CXX object src/preproc/CMakeFiles/preproc.dir/string_parser.cpp.o
[ 51%] Building CXX object src/preproc/CMakeFiles/preproc.dir/utf8.cpp.o
[ 50%] Building CXX object src/preproc/CMakeFiles/preproc.dir/preproc.cpp.o
[ 53%] Linking C executable bin2c
[ 54%] Linking C executable gbafix
[ 54%] Built target bin2c
[ 54%] Built target gbafix
[ 56%] Linking C executable gbagfx
[ 56%] Built target gbagfx
[ 58%] Linking C executable aif2pcm
[ 59%] Linking CXX executable util_dummy
[ 59%] Built target aif2pcm
[ 59%] Built target util_dummy
[ 61%] Linking CXX executable preproc
[ 61%] Built target preproc
[ 62%] Linking CXX executable mid2agb
[ 62%] Built target mid2agb
[ 64%] Linking CXX executable agb2mid
[ 64%] Built target agb2mid
[ 66%] Linking CXX static library libfmt.a
[ 66%] Built target fmt
[ 67%] Building CXX object src/scaninc/CMakeFiles/scaninc.dir/c_file.cpp.o
[ 69%] Building CXX object src/scaninc/CMakeFiles/scaninc.dir/asm_file.cpp.o
[ 70%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/assets/aif.cpp.o
[ 72%] Building CXX object src/scaninc/CMakeFiles/scaninc.dir/source_file.cpp.o
[ 74%] Building CXX object src/scaninc/CMakeFiles/scaninc.dir/scaninc.cpp.o
[ 75%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/assets/asset.cpp.o
[ 79%] Building CXX object src/tmc_strings/CMakeFiles/tmc_strings.dir/main.cpp.o
[ 77%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/assets/animation.cpp.o
[ 80%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/assets/macroasm.cpp.o
[ 82%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/assets/gfx.cpp.o
[ 83%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/assets/frameobjlists.cpp.o
[ 85%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/assets/spriteframe.cpp.o
[ 87%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/assets/palette.cpp.o
[ 88%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/assets/midi.cpp.o
[ 90%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/assets/tileset.cpp.o
[ 91%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/main.cpp.o
[ 93%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/offsets.cpp.o
[ 95%] Building CXX object src/asset_processor/CMakeFiles/asset_processor.dir/util.cpp.o
In file included from /home/corey/stuff/projects/tmc/tools/src/asset_processor/assets/spriteframe.cpp:2:
/home/corey/stuff/projects/tmc/tools/src/asset_processor/./reader.h: In member function ‘s8 Reader::read_s8()’:
/home/corey/stuff/projects/tmc/tools/src/asset_processor/./reader.h:16:57: error: conversion to ‘s8’ {aka ‘signed char’} from ‘char’ may change the sign of the result [-Werror=sign-conversion]
   16 |         return data[static_cast<unsigned long>(cursor++)];
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
In file included from /home/corey/stuff/projects/tmc/tools/src/asset_processor/assets/frameobjlists.cpp:2:
/home/corey/stuff/projects/tmc/tools/src/asset_processor/./reader.h: In member function ‘s8 Reader::read_s8()’:
/home/corey/stuff/projects/tmc/tools/src/asset_processor/./reader.h:16:57: error: conversion to ‘s8’ {aka ‘signed char’} from ‘char’ may change the sign of the result [-Werror=sign-conversion]
   16 |         return data[static_cast<unsigned long>(cursor++)];
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
In file included from /home/corey/stuff/projects/tmc/tools/src/asset_processor/assets/animation.cpp:2:
/home/corey/stuff/projects/tmc/tools/src/asset_processor/./reader.h: In member function ‘s8 Reader::read_s8()’:
/home/corey/stuff/projects/tmc/tools/src/asset_processor/./reader.h:16:57: error: conversion to ‘s8’ {aka ‘signed char’} from ‘char’ may change the sign of the result [-Werror=sign-conversion]
   16 |         return data[static_cast<unsigned long>(cursor++)];
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
In file included from /home/corey/stuff/projects/tmc/tools/src/asset_processor/assets/midi.cpp:2:
/home/corey/stuff/projects/tmc/tools/src/asset_processor/./reader.h: In member function ‘s8 Reader::read_s8()’:
/home/corey/stuff/projects/tmc/tools/src/asset_processor/./reader.h:16:57: error: conversion to ‘s8’ {aka ‘signed char’} from ‘char’ may change the sign of the result [-Werror=sign-conversion]
   16 |         return data[static_cast<unsigned long>(cursor++)];
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
cc1plus: all warnings being treated as errors
make[3]: *** [src/asset_processor/CMakeFiles/asset_processor.dir/build.make:188: src/asset_processor/CMakeFiles/asset_processor.dir/assets/spriteframe.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[3]: *** [src/asset_processor/CMakeFiles/asset_processor.dir/build.make:90: src/asset_processor/CMakeFiles/asset_processor.dir/assets/animation.cpp.o] Error 1
[ 96%] Linking CXX executable scaninc
cc1plus: all warnings being treated as errors
make[3]: *** [src/asset_processor/CMakeFiles/asset_processor.dir/build.make:118: src/asset_processor/CMakeFiles/asset_processor.dir/assets/frameobjlists.cpp.o] Error 1
[ 96%] Built target scaninc
cc1plus: all warnings being treated as errors
make[3]: *** [src/asset_processor/CMakeFiles/asset_processor.dir/build.make:160: src/asset_processor/CMakeFiles/asset_processor.dir/assets/midi.cpp.o] Error 1
[ 98%] Linking CXX executable tmc_strings
[ 98%] Built target tmc_strings
make[2]: *** [CMakeFiles/Makefile2:451: src/asset_processor/CMakeFiles/asset_processor.dir/all] Error 2
make[1]: *** [Makefile:156: all] Error 2
make: *** [Makefile:33: tools/bin] Error 2
```

**Comment by coreybruce** [comment]
Wait why is this closed? Did you read the log? Its failing to run, this issue isn't completed

**Comment by notyourav** [comment]
This should have been fixed

**Comment by coreybruce** [comment]
Hey just replying back to let you know that it isn't fixed, still not sure why you closed this with no reply and assumed it was fixed.

```
[ 96%] Linking CXX executable scaninc
cc1plus: all warnings being treated as errors
make[3]: *** [src/asset_processor/CMakeFiles/asset_processor.dir/build.make:118: src/asset_processor/CMakeFiles/asset_processor.dir/assets/frameobjlists.cpp.o] Error 1
[ 96%] Built target scaninc
cc1plus: all warnings being treated as errors
make[3]: *** [src/asset_processor/CMakeFiles/asset_processor.dir/build.make:160: src/asset_processor/CMakeFiles/asset_processor.dir/assets/midi.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:451: src/asset_processor/CMakeFiles/asset_processor.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX executable tmc_strings
[ 98%] Built target tmc_strings
make[1]: *** [Makefile:156: all] Error 2
make: *** [Makefile:33: tools/bin] Error 2
```

Seems to be failing on ```make tools```

**Comment by notyourav** [comment]
Oops, thats my bad.

I just pushed a fix that specifies char signedness in that spot, it should build now!

**Comment by coreybruce** [comment]
haha oh okay, I'll try it again soon and let you know how it goes :+1:

**Comment by Henny022p** [comment]
Does this problem still exist?
Otherwise I'll close this issue.

**Comment by coreybruce** [comment]
Yeah just close it for now, I don't have to time to relook at this issue sorry
